blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/<str:slug>/', BlogDetailView.as_view(), name='blog_detail')
]

client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
                          CityCreateView)

app_name = ClientConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/get/<str:slug>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_form'),
    path('clients/city/create/', CityCreateView.as_view(), name='city_form'),
    path('clients/update/<str:slug>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<str:slug>/', ClientDeleteView.as_view(), name='client_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter.urls', namespace='newsletter')),
    path('', include('client.urls', namespace='client')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, NewsletterAttemptsListView, NewsletterAttemptsDetailView, index, \
    regular_newsletter_manager, regular_newsletters_report, set_schedule, invalid_newsletter_settings

app_name = NewsletterConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletters/detail/<str:slug>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletters/update/<str:slug>/', NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletters/delete/<str:slug>', NewsletterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletters/attempts-report/', NewsletterAttemptsListView.as_view(), name='attempts_list'),
    path('newsletters/reports/<int:pk>/', NewsletterAttemptsDetailView.as_view(), name='attempt_responses_detail'),
    path('newsletters/control-panel/', regular_newsletter_manager, name='control_panel'),
    path('newsletters/general-report/', regular_newsletters_report, name='regular_newsletters_report'),
    path('newsletters/schedule-settings/', set_schedule, name='set_schedule'),
    path('newsletters/control-panel/invalid-settings/<str:slug>/', invalid_newsletter_settings,
         name='invalid_newsletter_settings'),
]

newsletter/models/email_server_response.py
from django.db import models

from newsletter.models.newsletter_attempts import NewsletterAttempts

NULLABLE = {'blank': True, 'null': True}


class EmailServerResponse(models.Model):
    attempt = models.ForeignKey(NewsletterAttempts, verbose_name='newsletter_attempt', on_delete=models.CASCADE,
                                related_name='email_response')
    recipient_email = models.EmailField(verbose_name='recipient_email')
    response = models.TextField(verbose_name='email_server_response', **NULLABLE)

    def __str__(self):
        return f'{self.attempt} ({self.recipient_email}, response - {self.response})'

    class Meta:
        verbose_name = 'Response'
        verbose_name_plural = 'Responses'

newsletter/views/index.py
import random

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from blog.models import Blog
from client.models import Client
from newsletter.models import Newsletter, NewsletterAttempts


@login_required
def index(request):
    all_newsletters = Newsletter.objects.filter(is_active=True)
    all_newsletters_launched = Newsletter.objects.filter(status='launched')
    all_newsletters_created = Newsletter.objects.filter(status='created')
    all_newsletters_finished = Newsletter.objects.filter(status='finished')
    all_attempts = NewsletterAttempts.objects.all()
    attempts_success = NewsletterAttempts.objects.filter(attempt_status='success')
    success_ratio = str(
        round(((attempts_success.count() / all_attempts.count()) * 100), 0)) + '%' if all_attempts.count() != 0 else '-'
    all_clients = Client.objects.all()
    all_clients_signed_up = Client.objects.filter(is_signed_up=True)
    signing_up_ratio = str(
        round(((all_clients_signed_up.count() / all_clients.count()) * 100),
              0)) + '%' if all_clients.count() != 0 else '-'
    all_blogs = Blog.objects.all()
    blogs_to_show = [all_blogs[x] for x in range(all_blogs.count())]
    random.shuffle(blogs_to_show)

    context = {
        'all_newsletters': all_newsletters,
        'all_newsletters_launched': all_newsletters_launched,
        'all_newsletters_created': all_newsletters_created,
        'all_newsletters_finished': all_newsletters_finished,
        'all_attempts': all_attempts,
        'attempts_success': attempts_success,
        'success_ratio': success_ratio,
        'all_clients': all_clients,
        'all_clients_signed_up': all_clients_signed_up,
        'signing_up_ratio': signing_up_ratio,
        'blogs_to_show': blogs_to_show[:3],
        'page_title': 'Main page'
    }
    return render(request, 'newsletter/index.html', context)

newsletter/views/newsletter.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.urls import reverse_lazy, reverse
from django.views import generic

from client.models import City
from newsletter.forms import NewsletterForm
from newsletter.models import Newsletter
from users.models import User


class NewsletterListView(LoginRequiredMixin, generic.ListView):
    model = Newsletter
    ordering = ('newsletter_user', 'pk')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)

        user = self.request.user
        group = Group.objects.get(name='manager')
        if group not in user.groups.all():
            queryset = queryset.filter(newsletter_user=user)
            if 'filter_form' in self.request.GET:
                status = self.request.GET.get('filter_status')
                if status != 'all':
                    queryset = queryset.filter(status=status)
                else:
                    return queryset
            return queryset
        else:
            if 'filter_form' in self.request.GET:
                status = self.request.GET.get('filter_status')
                user_email = self.request.GET.get('email_filter_user')
                if status == 'all' and user_email != 'all':
                    user_to_filter = User.objects.get(email=user_email)
                    queryset = queryset.filter(newsletter_user=user_to_filter)
                elif user_email == 'all' and status != 'all':
                    queryset = queryset.filter(status=status)
                elif user_email != 'all' and status != 'all':
                    user_to_filter = User.objects.get(email=user_email)
                    queryset = queryset.filter(status=status, newsletter_user=user_to_filter)
                else:
                    return queryset
            return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Newsletters list'
        context['all_cities'] = City.objects.all()
        context['all_users'] = User.objects.all()
        context['all_statuses'] = [status[0] for status in Newsletter.STATUS_CHOICE]
        return context


class NewsletterDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newsletter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Newsletters detail'
        return context


class NewsletterCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newsletter
    form_class = NewsletterForm
    extra_context = {'page_title': 'Create a newsletter'}

    def get_success_url(self):
        return reverse('newsletter:newsletter_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            self.object.newsletter_user = self.request.user
            self.object.save()
            return super().form_valid(form)


class NewsletterUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newsletter
    form_class = NewsletterForm

    def get_success_url(self):
        return reverse('newsletter:newsletter_detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Update newsletter'
        return context


class NewsletterDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newsletter
    success_url = reverse_lazy('newsletter:newsletter_list')
    extra_context = {'page_title': 'Delete newsletter'}

newsletter/views/newsletter_attempt.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.views import generic

from newsletter.models import NewsletterAttempts, Newsletter
from users.models import User


class NewsletterAttemptsListView(LoginRequiredMixin, generic.ListView):
    model = NewsletterAttempts
    ordering = ('-last_attempt',)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Newsletter attempts'
        context['all_newsletters'] = Newsletter.objects.all()
        context['all_users'] = User.objects.all()
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        user = self.request.user
        group = Group.objects.get(name='manager')
        if group not in user.groups.all():
            user_newsletters = Newsletter.objects.filter(newsletter_user=user)
            queryset = queryset.filter(newsletter__in=user_newsletters)
            if 'filter_form' in self.request.GET:
                newsletter_pk = self.request.GET.get('filter_newsletter')
                if newsletter_pk != 'all':
                    newsletter = Newsletter.objects.get(pk=newsletter_pk)
                    queryset = queryset.filter(newsletter=newsletter)
                else:
                    return queryset
            return queryset

        else:
            if 'filter_form' in self.request.GET:
                newsletter_pk = self.request.GET.get('filter_newsletter')
                user_email = self.request.GET.get('email_filter_user')
                if newsletter_pk == 'all' and user_email != 'all':
                    user_to_filter = User.objects.get(email=user_email)
                    user_newsletters = Newsletter.objects.filter(newsletter_user=user_to_filter)
                    queryset = queryset.filter(newsletter__in=user_newsletters)
                elif user_email == 'all' and newsletter_pk != 'all':
                    newsletter = Newsletter.objects.get(pk=newsletter_pk)
                    queryset = queryset.filter(newsletter=newsletter)
                elif newsletter_pk != 'all' and user_email != 'all' :
                    user_to_filter = User.objects.get(email=user_email)
                    user_newsletters = Newsletter.objects.filter(newsletter_user=user_to_filter)
                    queryset = queryset.filter(newsletter__in=user_newsletters)
                    newsletter = Newsletter.objects.get(pk=newsletter_pk)
                    queryset = queryset.filter(newsletter=newsletter)
                else:
                    return queryset
            return queryset


class NewsletterAttemptsDetailView(LoginRequiredMixin, generic.DetailView):
    model = NewsletterAttempts

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Newsletters attempt detail'
        return context

newsletter/views/regular_newsletters_manager.py
from datetime import datetime

import pytz
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django_celery_beat.models import PeriodicTask

from config import settings
from newsletter.models import Newsletter
from newsletter.tasks import set_regular_newsletter_schedule, disable_launched_newsletter_task, set_disabler_schedule, \
    send_newsletter_task
from users.models import User


@login_required
def regular_newsletter_manager(request):
    if request.method == 'POST':
        if 'newsletter_launch' in request.POST:
            newsletter_pk = request.POST.get('pk_newsletter_launch')
            newsletter = Newsletter.objects.get(pk=newsletter_pk)
            start_campaign = newsletter.start_campaign
            actual_time = datetime.now(tz=pytz.timezone(settings.TIME_ZONE))
            if start_campaign < actual_time:
                return redirect(
                    reverse('newsletter:invalid_newsletter_settings', kwargs={'slug': newsletter.slug}))
            else:
                set_regular_newsletter_schedule.delay(newsletter_pk)
                set_disabler_schedule(newsletter_pk)
                return redirect(reverse('newsletter:newsletter_list'))
        if 'newsletter_remove' in request.POST:
            if not request.user.has_perm('newsletter.remove_regular_newsletter'):
                raise Http404('You don\'t have access to this action! PLease contact your manager.')
            newsletter_pk = request.POST.get('pk_newsletter_remove')
            disable_launched_newsletter_task(newsletter_pk)
            return redirect(reverse('newsletter:newsletter_list'))
        if 'newsletter_one_off' in request.POST:
            newsletter_pk = request.POST.get('newsletter_one_off')
            send_newsletter_task(newsletter_pk)
            return redirect(reverse('newsletter:attempts_list'))
    else:
        user = request.user
        available_user_newsletters = Newsletter.objects.filter(newsletter_user=user, status='created')
        all_newsletters_launched = Newsletter.objects.filter(status='launched')
        all_newsletters_total = Newsletter.objects.all()
        context = {'available_user_newsletters': available_user_newsletters,
                   'newsletters_list_launched': all_newsletters_launched,
                   'page_title': 'Launch newsletter', 'all_newsletters_total': all_newsletters_total}
        return render(request, 'newsletter/control_panel.html', context)


@login_required
def regular_newsletters_report(request):
    periodic_tasks = PeriodicTask.objects.all()
    all_newsletters = Newsletter.objects.all()
    tasks_status = {}
    for task in periodic_tasks:
        task_args_newsletter_pk = task.args
        if not task.one_off and not task_args_newsletter_pk == '[]':
            newsletter = all_newsletters.filter(pk=eval(task_args_newsletter_pk)[0]).first()
            tasks_status[eval(task.args)[0]] = {
                'newsletter_id': newsletter.pk,
                'newsletter_title': newsletter.newsletter,
                'schedule': task.crontab.human_readable,
                'total_run_count': task.total_run_count,
                'start_time': task.start_time,
                'finish_time': newsletter.finish_campaign,
                'newsletter_user': newsletter.newsletter_user.email,
                'enabled': task.enabled
            }

    if 'filter_form' in request.GET:
        newsletter_pk = request.GET.get('filter_newsletter')
        user_email = request.GET.get('email_filter_user')
        if newsletter_pk == 'all' and user_email != 'all':
            tasks_status = {k: v for k, v in tasks_status.items() if v['newsletter_user'] == user_email}
        elif newsletter_pk != 'all' and user_email == 'all':
            tasks_status = {k: v for k, v in tasks_status.items() if k == newsletter_pk}
        elif user_email != 'all' and newsletter_pk != 'all':
            tasks_status = {k: v for k, v in tasks_status.items() if k == newsletter_pk}
            tasks_status = {k: v for k, v in tasks_status.items() if v['newsletter_user'] == user_email}

    all_newsletters = Newsletter.objects.all()
    all_users = User.objects.all()
    context = {'tasks_status': tasks_status, 'all_newsletters': all_newsletters, 'all_users': all_users}

    return render(request, 'newsletter/regular_newsletters_report.html', context)


def invalid_newsletter_settings(request, slug):
    newsletter = Newsletter.objects.get(slug=slug)
    context = {
        'actual_time': datetime.now(tz=pytz.timezone(settings.TIME_ZONE)),
        'newsletter': newsletter,
        'message': f'Please, check and edit the "{newsletter.newsletter}" newsletter settings. '
                   f'"start_campaign" cannot be earlier that actual time'
    }
    return render(request, 'newsletter/invalid_regular_newsletter.html', context)

newsletter/templates/newsletter/newsletter_detail.html
{% extends 'newsletter/base.html'%}
{% block content %}

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'newsletter:newsletter_list'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Newsletter list
            </a>
        </div>
    </header>

    <div class="row container-fluid" style="max-height: 555px;
            overflow-y: auto;">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-header">
                    <p class="fw-bold fs-2">Details</p>
                </div>
                <div class="card-body">
                    <p class="fw-medium"><strong>Newsletter:</strong> {{object.newsletter}}</p>
                    <p class="fw-medium"><strong>Id:</strong> {{object.pk}}</p>
                    <p class="fw-medium"><strong>Duration</strong>:
                        <br> {{object.start_campaign}} -> {{object.finish_campaign}}</p>
                    <p class="fw-medium"><strong>Status:</strong> {{object.status}}</p>
                    <p class="fw-medium"><strong>Regularity:</strong> {{object.regularity.mode_name }}</p>
                    <p class="fw-medium"><strong>Activity:</strong>
                        {% if object.is_active %}active
                        {%else%}'deactivated' and not in the list{%endif%}</p>
                    <p class="fw-medium"><strong>Created at:</strong> {{object.created}}</p>
                    <p class="fw-medium"><strong>Owner:</strong> {{object.newsletter_user}}</p>
                    <p class="fw-medium"><strong>Inform clients from:</strong>
                        {% for city in object.newsletter_cities.all %}
                            {{city}}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                </div>
                <div class="card-footer">

                        {% if request.user == object.newsletter_user %}
                        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                            <a class="btn btn-outline-info rounded-pill"
                               href="{% url 'newsletter:newsletter_update' object.slug %}">Edit</a>
                            <a class="btn btn-outline-danger rounded-pill"
                               href="{% url 'newsletter:newsletter_delete' object.slug %}">Delete</a>
                        </nav>
                        {% else %}
                        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                            <a class="btn btn-outline-info rounded-pill"
                               data-bs-toggle="popover"
                               data-bs-title="Access issue"
                               data-bs-content="You can access and edit your own newsletters only!">Edit</a>
                            <a class="btn btn-outline-danger rounded-pill"
                               data-bs-toggle="popover"
                               data-bs-title="Access issue"
                               data-bs-content="You can access and edit your own newsletters only!">Delete</a>
                        </nav>
                        {% endif %}

                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <p class="fw-bold fs-2">Newsletter content</p>
                </div>
                <div class="card-body">
                    <p class="fw-medium"><strong>Message subject</strong>: {{object.subject}}</p>
                    <p class="fw-medium"><strong>Content</strong>: {{object.content}}</p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends 'newsletter/base.html'%}
{% block content %}
{% load my_tags %}


<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-left: 30px"
               href="{% url 'newsletter:control_panel'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Newsletters control panel
            </a>

        </div>
    </header>
    {% if user|has_group:"manager" %}
    <div class="row col-8">
    {% else %}
    <div class="row col-6">
    {% endif %}
            <form class="form-control " method="get" action="{% url 'newsletter:newsletter_list' %}" name="filter_form">
                <div class="row">
                    {% if user|has_group:"manager" %}
                    <div class="col-4">
                    {% else %}
                    <div class="col-8">
                    {% endif %}
                        <label>Select status:</label>
                        <select class="form-select form-select-sm required" aria-label=".form-select-sm example"
                                name="filter_status">
                                <option value='all'>
                                    All statuses
                                </option>
                            {% for status in all_statuses %}
                                <option value='{{status}}'>{{status}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% if user|has_group:"manager" %}
                    <div class="col-5">
                    <label>Select an owner:</label>
                        <select class="form-select form-select-sm required" aria-label=".form-select-sm example"
                                name="email_filter_user">
                                <option value="all">
                                    All users
                                </option>
                            {% for u in all_users %}
                                {% if request.user == u %}
                                    <option value='{{u.email}}' class="text-primary">{{u.email}}</option>
                                {% else %}
                                    <option value='{{u.email}}'>{{u.email}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    {% endif %}
                    <div class="col-3 d-flex justify-content-end align-items-center">
                        <button class="btn btn-secondary float-end"
                                type="submit" name="filter_form">Filter</button>
                    </div>
                </div>
            </form>
    </div>

    <div class="container d-flex justify-content-center align-items-start mt-3">
        <div class="container-fluid" style="max-height: 350px;
            overflow-y: auto;">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Newsletter</th>
                    <th scope="col">Status</th>
                    <th scope="col">Regularity</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Start time</th>
                    <th scope="col">Finish time</th>
                </tr>
                </thead>
                <tbody class="table-group-divider">

                {% for object in object_list %}
                {% if user|has_group:"manager" %}
                <tr>
                    <th scope="row">{{ object.pk}}</th>
                    <td><a href="{% url 'newsletter:newsletter_detail' object.slug %}">{{ object.newsletter }}</a></td>
                    <td>{{ object.status}}</td>
                    <td>{{ object.regularity}}</td>
                    {% if user == object.newsletter_user %}
                    <td><strong class="text-primary">{{ object.newsletter_user }}</strong></td>
                    {% else %}
                    <td>{{ object.newsletter_user }}</td>
                    {% endif %}
                    <td>{{ object.start_campaign }}</td>
                    <td>{{ object.finish_campaign }}</td>
                </tr>
                {% else %}
                <tr>
                    <th scope="row">{{ object.pk}}</th>
                    <td><a href="{% url 'newsletter:newsletter_detail' object.slug %}">{{ object.newsletter }}</a></td>
                    <td>{{ object.status}}</td>
                    <td>{{ object.regularity}}</td>
                    <td>{{ object.newsletter_user }}</td>
                    <td>{{ object.start_campaign }}</td>
                    <td>{{ object.finish_campaign }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="m-4 float-end">
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="btn btn-outline-primary rounded-pill"
                   href="{% url 'newsletter:newsletter_create' %}">Create newsletter</a>
            </nav>
    </div>
</div>

{% endblock %}

newsletter/templates/newsletter/newslettersettings_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

newsletter/templates/newsletter/newslettersettings_list.html
{% extends 'newsletter/base.html'%}
{% block content %}


<div class="container px-4 py-5 scrollarea" id="featured-3">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">

        {% for object in object_list%}
        <div class="feature col">
            <div class="feature-icon d-inline-flex align-items-center
            justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                <svg class="bi" width="1em" height="1em">
                    <use xlink:href="#collection"/>
                </svg>
            </div>
            <h3 class="fs-2 text-body-emphasis">{{ object.subject }}</h3>
            <p>{{ object.content }}</p>
            <a href="#" class="icon-link">
                Details
                <svg class="bi">
                    <use xlink:href="#chevron-right"/>
                </svg>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}