blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/<str:slug>/', BlogDetailView.as_view(), name='blog_detail')
]

client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
                          CityCreateView)

app_name = ClientConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/get/<str:slug>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_form'),
    path('clients/city/create/', CityCreateView.as_view(), name='city_form'),
    path('clients/update/<str:slug>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<str:slug>/', ClientDeleteView.as_view(), name='client_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter.urls', namespace='newsletter')),
    path('', include('client.urls', namespace='client')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, NewsletterAttemptsListView, NewsletterAttemptsDetailView, index, \
    regular_newsletter_manager, regular_newsletters_report, set_schedule, invalid_newsletter_settings

app_name = NewsletterConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletters/detail/<str:slug>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletters/update/<str:slug>/', NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletters/delete/<str:slug>', NewsletterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletters/attempts-report/', NewsletterAttemptsListView.as_view(), name='attempts_list'),
    path('newsletters/reports/<int:pk>/', NewsletterAttemptsDetailView.as_view(), name='attempt_responses_detail'),
    path('newsletters/control-panel/', regular_newsletter_manager, name='control_panel'),
    path('newsletters/general-report/', regular_newsletters_report, name='regular_newsletters_report'),
    path('newsletters/schedule-settings/', set_schedule, name='set_schedule'),
    path('newsletters/control-panel/invalid-settings/<str:slug>/', invalid_newsletter_settings,
         name='invalid_newsletter_settings'),
]

client/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode

NULLABLE = {'blank': True, 'null': True}


class City(models.Model):
    city = models.CharField(verbose_name='city_name', max_length=50, unique=True)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.city


class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name='client_name', unique=True)
    email = models.EmailField(max_length=50, verbose_name='client_email', unique=True)
    slug = models.SlugField(verbose_name='slug', **NULLABLE)
    is_signed_up = models.BooleanField(verbose_name='is_signed_up', default=True)
    is_active = models.BooleanField(verbose_name='is_active', default=True)
    comments = models.TextField(verbose_name='additional_info', **NULLABLE)
    created = models.DateTimeField(verbose_name='created', auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='user_clients', **NULLABLE)
    city = models.ForeignKey(
        City, on_delete=models.SET_NULL, related_name='city_clients', verbose_name='client_city', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.email}'

    def save(self, *args, **kwargs):
        if self.slug:
            super().save(*args, **kwargs)
        else:
            self.slug = slugify(unidecode(self.name))
            super().save(**kwargs)

    def delete(self, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'

client/forms.py
from django import forms

from client.models import Client, City


class ClientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'comments':
                self.fields[field_name] = forms.CharField(
                    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '6'}))
            if field_name == 'city':
                self.fields[field_name] = forms.ModelChoiceField(
                    queryset=City.objects.all(), )
                self.fields[field_name].widget.attrs['class'] = 'form-control'
            if field_name == 'is_signed_up':
                self.fields[field_name] = forms.BooleanField(
                    required=False, widget=forms.CheckboxInput(attrs={'class': 'checkbox-small'}), label='Is signed up')

    class Meta:
        model = Client
        exclude = ('is_active', 'user', 'slug')


class CityForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = City
        fields = ('city',)

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from client.forms import ClientForm, CityForm
from client.models import Client, City
from users.models import User


class ClientListView(LoginRequiredMixin, generic.ListView):
    model = Client
    ordering = ('user', 'pk',)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Clients list'
        context['all_users'] = User.objects.all()
        context['all_cities'] = City.objects.all()
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)
        user = self.request.user

        group = Group.objects.get(name='manager')
        if group not in user.groups.all():
            queryset = queryset.filter(user=user)
            if 'filter_form' in self.request.GET:
                city = self.request.GET.get('filter_city')
                if city != 'all':
                    city_to_filter = City.objects.get(city=city)
                    queryset = queryset.filter(city=city_to_filter)
                else:
                    return queryset
            return queryset
        else:
            if 'filter_form' in self.request.GET:
                city = self.request.GET.get('filter_city')
                user_email = self.request.GET.get('email_filter_user')
                if city == 'all' and user_email != 'all':
                    user_to_filter = User.objects.get(email=user_email)
                    queryset = queryset.filter(user=user_to_filter)
                elif user_email == 'all' and city != 'all':
                    city_to_filter = City.objects.get(city=city)
                    queryset = queryset.filter(city=city_to_filter)
                elif user_email != 'all' and city != 'all':
                    city_to_filter = City.objects.get(city=city)
                    user_to_filter = User.objects.get(email=user_email)
                    queryset = queryset.filter(city=city_to_filter, user=user_to_filter)
                else:
                    return queryset
            return queryset

    def post(self, *args, **kwargs):

        if 'sign_up_toggle' in self.request.POST:
            pk = self.request.POST.get('pk_sign_up_toggle')
            client = Client.objects.get(pk=pk)
            client.is_signed_up = not client.is_signed_up
            client.save()

        return redirect(reverse('client:client_list'))


class ClientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Client

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Client details'
        return context


class ClientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('client:client_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            self.object.user = self.request.user
            self.object.save()
            return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Create a client'
        return context


class CityCreateView(LoginRequiredMixin, generic.CreateView):
    model = City
    form_class = CityForm

    def get_success_url(self):
        return reverse('client:client_list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Create a city'
        return context


class ClientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('client:client_detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Update a client'
        return context


class ClientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Client
    success_url = reverse_lazy('client:client_list')
    extra_context = {'page_title': 'Delete a client'}

client/templates/client/city_form.html
{% extends 'newsletter/base.html'%}
{% block content %}

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'client:client_list'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Clients list
            </a>
        </div>
    </header>

    <div class="container d-flex justify-content-center align-items-start">
        <div class="col-sm-8 mb-3 mb-sm-0">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-header">
                        <h1>Add a city</h1>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form.as_p }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_confirm_delete.html
{% extends 'newsletter/base.html'%}
{% block content %}


<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'client:client_list'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Clients list
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none" style="margin-left: 30px"
               href="{% url 'client:client_detail' object.slug %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Client detail
            </a>
        </div>
    </header>


    <div class="card">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="card-header">
                <h1>Deleting confirmation</h1>
            </div>

            <div class="card-body">
                Are you sure you want to delete <strong>{{ object.name }}</strong> client?
            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-danger">
                    Delete
                </button>
            </div>
        </form>
    </div>

</div>

{% endblock %}

client/templates/client/client_detail.html
{% extends 'newsletter/base.html'%}
{% block content %}

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'client:client_list'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Clients list
            </a>
        </div>
    </header>

    <div class="row container-fluid" style="max-height: 500px;
            overflow-y: auto;">
        <div class="col-sm-8 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-header">
                    <p class="fw-bold fs-2">Client details</p>
                </div>
                <div class="card-body">
                    <p class="fw-medium"><strong>Client name:</strong> {{object.name}}</p>
                    <p class="fw-medium"><strong>Client email:</strong> {{object.email}}</p>
                    <p class="fw-medium"><strong>Added by:</strong> {{object.user}}</p>
                    <p class="fw-medium"><strong>Added at:</strong> {{object.created}}</p>
                    <p class="fw-medium"><strong>Additional info:</strong> {{object.comments}}</p>
                    <p class="fw-medium"><strong>Is signed up:</strong> {% if object.is_signed_up %}Yes{% else %} No {% endif %}</p>
                    <p class="fw-medium"><strong>Is active:</strong> - {{object.is_active}}</p>
                </div>
                <div class="card-footer">
                      {% if user == object.user %}
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="btn btn-outline-info rounded-pill"
                   href="{% url 'client:client_update' object.slug %}">Edit</a>
                <a class="btn btn-outline-danger rounded-pill"
                   href="{% url 'client:client_delete' object.slug %}">Delete</a>
            </nav>
            {% else %}
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="btn btn-outline-info rounded-pill"
                   data-bs-toggle="popover"
                   data-bs-title="Access issue"
                   data-bs-content="You can only access and edit clients that have been added by you!">Edit</a>
                <a class="btn btn-outline-danger rounded-pill"
                   data-bs-toggle="popover"
                   data-bs-title="Access issue"
                   data-bs-content="You can only access and edit clients that have been added by you!">Delete</a>
            </nav>
            {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

client/templates/client/client_list.html
{% extends 'newsletter/base.html'%}
{% block content %}
{% load my_tags %}

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'newsletter:control_panel' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Newsletters control panel
            </a>
        </div>
    </header>


    {% if user|has_group:"manager" %}
    <div class="row col-8">
        {% else %}
        <div class="row col-6">
            {% endif %}
            <form class="form-control " method="get" action="{% url 'client:client_list' %}" name="filter_form">
                <div class="row">
                    {% if user|has_group:"manager" %}
                    <div class="col-4">
                        {% else %}
                        <div class="col-8">
                            {% endif %}
                            <label>Select a city:</label>
                            <select class="form-select form-select-sm required" aria-label=".form-select-sm example"
                                    name="filter_city">
                                <option value='all'>
                                    All cities
                                </option>
                                {% for city in all_cities %}
                                <option value='{{city.city}}'>{{city}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        {% if user|has_group:"manager" %}
                        <div class="col-5">
                            <label>Added by:</label>
                            <select class="form-select form-select-sm required" aria-label=".form-select-sm example"
                                    name="email_filter_user">
                                <option value="all">
                                    All users
                                </option>
                                {% for u in all_users %}
                                {% if request.user == u %}
                                <option value='{{u.email}}' class="text-primary">{{u.email}}</option>
                                {% else %}
                                <option value='{{u.email}}'>{{u.email}}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        {% endif %}

                        <div class="col-3 d-flex justify-content-end align-items-center">
                            <button class="btn btn-secondary float-end"
                                    type="submit" name="filter_form">Filter
                            </button>
                        </div>
                    </div>
            </form>
        </div>

        <div class="container d-flex justify-content-center align-items-start mt-3">
            <div class="container-fluid" style="max-height: 350px;
            overflow-y: auto;">
                <table class="table table-striped">
                    <thead>
                    <tr class="sticky-top">
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">City</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Sign-up/Unsign</th>
                    </tr>
                    </thead>
                    <tbody class="table-group-divider">
                    {% for object in object_list %}
                    {% if user|has_group:"manager" %}
                    <tr>
                        <th scope="row">{{ object.pk}}</th>
                        <td><a href="{% url 'client:client_detail' object.slug %}">{{ object.name }}</a></td>
                        <td>{{ object.email}}</td>
                        <td>{{ object.city}}</td>
                        {% if user == object.user %}
                        <td><strong class="text-primary">{{ object.user }}</strong></td>
                        {% else %}
                        <td>{{ object.user }}</td>
                        {% endif %}
                        <td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="pk_sign_up_toggle" value="{{ object.pk }}">
                                {% if request.user == object.user %}
                                <button class="btn btn-outline-primary" type="submit" name="sign_up_toggle">
                                    {% if object.is_signed_up %}Unsubscribe
                                    {% else%} Sign up
                                    {% endif %}
                                </button>
                                {% else %}
                                <button class="btn btn-outline-secondary disabled" type="submit" name="sign_up_toggle">
                                    {% if object.is_signed_up %}Unsubscribe
                                    {% else%} Sign up
                                    {% endif %}
                                </button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <th scope="row">{{ object.pk }}</th>
                        <td><a href="{% url 'client:client_detail' object.slug %}">{{ object.name }}</a></td>
                        <td>{{ object.email}}</td>
                        <td>{{ object.city}}</td>
                        {% if user == object.user %}
                        <td>{{ object.user }}</td>
                        {% else %}
                        <td>{{ object.user }}</td>
                        {% endif %}
                        <td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="pk_sign_up_toggle" value="{{ object.pk }}">
                                <button class="btn btn-outline-primary" type="submit" name="sign_up_toggle">
                                    {% if object.is_signed_up %}Unsubscribe
                                    {% else%} Sign up
                                    {% endif %}
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="m-4 float-end">
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="btn btn-outline-primary rounded-pill"
                   href="{% url 'client:client_form' %}">Add client</a>
            </nav>
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="btn btn-outline-primary rounded-pill"
                   href="{% url 'client:city_form' %}">Add city</a>
            </nav>
        </div>
    </div>
</div>
{% endblock %}