blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/<str:slug>/', BlogDetailView.as_view(), name='blog_detail')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter.urls', namespace='newsletter')),
    path('', include('client.urls', namespace='client')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, NewsletterAttemptsListView, NewsletterAttemptsDetailView, index, \
    regular_newsletter_manager, regular_newsletters_report, set_schedule, invalid_newsletter_settings

app_name = NewsletterConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletters/detail/<str:slug>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletters/update/<str:slug>/', NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletters/delete/<str:slug>', NewsletterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletters/attempts-report/', NewsletterAttemptsListView.as_view(), name='attempts_list'),
    path('newsletters/reports/<int:pk>/', NewsletterAttemptsDetailView.as_view(), name='attempt_responses_detail'),
    path('newsletters/control-panel/', regular_newsletter_manager, name='control_panel'),
    path('newsletters/general-report/', regular_newsletters_report, name='regular_newsletters_report'),
    path('newsletters/schedule-settings/', set_schedule, name='set_schedule'),
    path('newsletters/control-panel/invalid-settings/<str:slug>/', invalid_newsletter_settings,
         name='invalid_newsletter_settings'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verify_email, UserUpdateView, user_list, UserCreateView, \
    UserDetailView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('users/login/', LoginView.as_view(), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
    path('users/registration/', RegisterView.as_view(), name='register'),
    path('users/registration/verification/<str:email>', verify_email, name='verify_email'),
    path('users/manager/list/', user_list, name='user_list'),
    path('users/manager/create-user/', UserCreateView.as_view(), name='user_form'),
    path('users/manager/user-detail/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('users/manager/user-delete/<int:pk>', UserDeleteView.as_view(), name='user_delete'),
    path('users/manager/update/<int:pk>', UserUpdateView.as_view(), name='user_form')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from users.manager import UserManager
from newsletter.models.newsletter import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='user_email', max_length=100, unique=True)
    phone = models.CharField(verbose_name='user_phone', max_length=50, **NULLABLE, unique=True)
    avatar = models.ImageField(verbose_name='user_avatar', upload_to='avatars/', **NULLABLE)
    verification_code = models.CharField(verbose_name='email_verification_code', **NULLABLE)
    is_verified = models.BooleanField(verbose_name='is_verified', default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def delete(self, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        permissions = [
            (
                'block_user',
                'can block users'
            ),
            (
                'set_schedule',
                'can set schedule'
            )
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.core.exceptions import ValidationError

from users.models import User


class LoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_verified:
            raise ValidationError('Your user is blocked! Please contact your manager.')
        else:
            super().confirm_login_allowed(user)


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'is_verified')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_verified':
                self.fields[field_name] = forms.BooleanField(
                    required=False, widget=forms.CheckboxInput(attrs={'class': 'checkbox-small'}), label=field_name)

newsletter/views/set_schedule.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.urls import reverse

from newsletter.models import Schedule
from users.services import get_wod_setting
from cron_descriptor.ExpressionDescriptor import get_description

@login_required
@permission_required('users.set_schedule', raise_exception=True)
def set_schedule(request):
    if request.method == 'POST':
        if 'daily' in request.POST:
            new_hour = request.POST.get('daily_hour')
            new_minute = request.POST.get('daily_minute')
            new_daily_settings = f'{new_minute} {new_hour} * * *'
            daily_mode = Schedule.objects.get(mode_name='daily')
            daily_mode.mode_settings = new_daily_settings
            daily_mode.save()
        if 'weekly' in request.POST:
            new_hour = request.POST.get('weekly_hour')
            new_minute = request.POST.get('weekly_minute')
            new_day = request.POST.get('weekly_day')
            new_weekly_settings = f'{new_minute} {new_hour} * * {get_wod_setting(new_day)}'
            weekly_mode = Schedule.objects.get(mode_name='weekly')
            weekly_mode.mode_settings = new_weekly_settings
            weekly_mode.save()
        if 'monthly' in request.POST:
            new_hour = request.POST.get('monthly_hour')
            new_minute = request.POST.get('monthly_minute')
            new_day = request.POST.get('monthly_day')
            new_monthly_settings = f'{new_minute} {new_hour} {new_day} * *'
            monthly_mode = Schedule.objects.get(mode_name='monthly')
            monthly_mode.mode_settings = new_monthly_settings
            monthly_mode.save()

        return redirect(reverse('newsletter:set_schedule'))

    else:
        all_schedules = Schedule.objects.all()
        hour_list = [str(x) for x in range(9, 19)]
        minute_list = ['15', '30', '45', '0']
        dow_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        dom_list = [str(x) for x in range(1, 32)]

        daily_settings = Schedule.objects.get(mode_name='daily')
        weekly_settings = Schedule.objects.get(mode_name='weekly')
        monthly_settings = Schedule.objects.get(mode_name='monthly')

        context = {
            'all_schedules': all_schedules,
            'minute_list': minute_list,
            'hour_list': hour_list,
            'dow_list': dow_list,
            'dom_list': dom_list,
            'page_title': 'Schedule settings',
            'human_readable_daily': get_description(daily_settings.mode_settings),
            'human_readable_weekly': get_description(weekly_settings.mode_settings),
            'human_readable_monthly': get_description(monthly_settings.mode_settings)
        }

    return render(request, 'newsletter/set_schedule.html', context)

users/views/email_verify.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.urls import reverse

from users.models import User


def verify_email(request, email):
    if request.method == 'POST':
        code = request.POST.get('code')
        user = User.objects.get(email=email)
        if user.verification_code == code:
            user.is_verified = True
            user.save()
            return redirect(reverse('users:login'))
        else:
            raise ValidationError('You have inputted the wrong verification code')
    else:
        context = {'page_title': 'Email verification'}
        return render(request, 'users/verify_email.html', context)

users/views/log_in_and_out.py
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView

from users.forms import LoginForm


class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Logging in'
        return context


class LogoutView(BaseLogoutView):
    pass

users/views/register.py
import random

from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from django.views import generic

from users.forms import UserRegisterForm
from users.models import User


class RegisterView(generic.CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            code = ''.join([str(random.randint(0, 9)) for _ in range(12)])
            self.object.verification_code = code
            self.object.save()
            send_mail(
                'Email verification',
                f'Your verification code - {code}. Please, use it for logging in.',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:verify_email', kwargs={'email': self.object.email})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Register'
        return context

users/views/set_schedule.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.urls import reverse

from newsletter.models import Schedule, Newsletter
from users.services import get_wod_setting

@login_required
@permission_required('users.set_schedule', raise_exception=True)
def set_schedule(request):

    if request.method == 'POST':
        if 'daily' in request.POST:
            new_hour = request.POST.get('daily_hour')
            new_minute = request.POST.get('daily_minute')
            new_daily_settings = f'{new_minute} {new_hour} * * *'
            daily_mode = Schedule.objects.get(mode_name='daily')
            daily_mode.mode_settings = new_daily_settings
            daily_mode.save()
        if 'weekly' in request.POST:
            new_hour = request.POST.get('weekly_hour')
            new_minute = request.POST.get('weekly_minute')
            new_day = request.POST.get('weekly_day')
            new_weekly_settings = f'{new_minute} {new_hour} * * {get_wod_setting(new_day)}'
            weekly_mode = Schedule.objects.get(mode_name='weekly')
            weekly_mode.mode_settings = new_weekly_settings
            weekly_mode.save()
        if 'monthly' in request.POST:
            new_hour = request.POST.get('monthly_hour')
            new_minute = request.POST.get('monthly_minute')
            new_day = request.POST.get('monthly_day')
            new_monthly_settings = f'{new_minute} {new_hour} {new_day} * *'
            monthly_mode = Schedule.objects.get(mode_name='monthly')
            monthly_mode.mode_settings = new_monthly_settings
            monthly_mode.save()

        return redirect(reverse('users:set_schedule'))

    else:
        all_schedules = Schedule.objects.all()
        hour_list = [str(x) for x in range(9, 19)]
        minute_list = ['15', '30', '45', '0']
        dow_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        dom_list = [str(x) for x in range(1, 32)]

        context = {
            'daily_settings': Schedule.objects.get(mode_name='daily'),
            'weekly_settings': Schedule.objects.get(mode_name='weekly'),
            'monthly_settings': Schedule.objects.get(mode_name='monthly'),
            'all_schedules': all_schedules,
            'minute_list': minute_list,
            'hour_list': hour_list,
            'dow_list': dow_list,
            'dom_list': dom_list,
            'page_title': 'Schedule settings'
        }

    return render(request, 'users/set_schedule.html', context)

users/views/users.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from client.models import Client
from newsletter.models import Newsletter
from users.forms import UserProfileForm
from users.models import User
from users.services import get_cached_users_for_list_table


@login_required
def user_list(request):
    context = {'object_list': get_cached_users_for_list_table(), 'page_title': 'Users list'}
    return render(request, 'users/user_list.html', context)


class UserCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:user_list')
    extra_context = {'page_title': 'Create user'}
    permission_required = 'users.add_user'


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserProfileForm
    extra_context = {'page_title': 'Update users'}
    permission_required = 'users.change_user'

    def get_success_url(self):
        return reverse('users:user_detail', kwargs={'pk': self.object.pk})


class UserDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = User
    success_url = reverse_lazy('users:user_list')
    extra_context = {'page_title': 'Delete user'}
    permission_required = 'users.delete_user'


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    extra_context = {'page_title': 'User detail'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = kwargs.get('object')
        context['user_clients'] = Client.objects.filter(user=user).count()
        context['newsletter_user'] = Newsletter.objects.filter(newsletter_user=user).count()
        return context

    def post(self, *args, **kwargs):

        if 'verify_toggle' in self.request.POST:
            pk = self.request.POST.get('pk_verify_toggle')
            user = User.objects.get(pk=pk)
            user.is_verified = not user.is_verified
            user.save()

        return redirect('users:user_detail', pk=self.kwargs['pk'])

users/templates/users/login.html
{% extends 'newsletter/base.html'%}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 60vh;">
    <div class="card">
        <form method="post" class="form-control" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="card-header">
                <h1>Authorization</h1>
            </div>

            <div class="card-body">
                <div class="form-group">
                    {{ form.as_p }}
                </div>
            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    Log in
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/login_warning.html
{% extends 'newsletter/base.html'%}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 60vh;">
    <div class="card">

        <div class="card-header">
            <h1>You have to log in first!</h1>
        </div>

        <div class="card-body">
            <a href="{% url 'users:login' %}" class="btn btn-primary">
                Go to log in
            </a>
        </div>
        <div class="card-footer">
        </div>

    </div>
</div>
{% endblock %}

users/templates/users/set_schedule.html
{% extends 'newsletter/base.html'%}
{% block content %}

<div class="container py-3">

    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
        </div>
    </header>

    <div class="row">

        <div class="col-sm-4 mb-3 mb-sm-0">
            <form class="form-control" method="post">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <p class="fw-bold fs-2">Daily</p>
                    </div>
                    <div class="card-body">
                        <p class="fw-medium"><strong>Active settings</strong>:<br>
                            <strong class="text-primary">{{ daily_settings }} / {{ daily_settings.mode_settings }}</strong>
                        </p>
                        <br>
                        <p class="fw-medium mt-3"><strong></strong>Select an hour:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="daily_hour"
                                required>
                            <option selected></option>
                            {% for h in hour_list %}
                            <option value='{{h}}'>{{h}}</option>
                            {% endfor %}
                        </select>
                        <br>
                        <p class="fw-medium"><strong></strong>Select a minute:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="daily_minute"
                                required>
                            <option selected></option>
                            {% for m in minute_list %}
                            <option value='{{m}}'>{{m}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="card-footer">
                        <div class="card-footer">
                            <button class="btn btn-outline-primary" type="submit" name="daily">Save changes</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-sm-4">
            <form class="form-control" method="post">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <p class="fw-bold fs-2">Weekly</p>
                    </div>
                    <div class="card-body">
                        <p class="fw-medium"><strong>Active settings</strong>:<br>
                             <strong class="text-primary">{{ weekly_settings }} / {{ weekly_settings.mode_settings }}</strong>
                        </p>
                        <p class="fw-medium"><strong></strong>Select an hour:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="weekly_hour"
                                required>
                            <option selected></option>
                            {% for h in hour_list %}
                            <option value='{{h}}'>{{h}}</option>
                            {% endfor %}
                        </select>
                        <p class="fw-medium"><strong></strong>Select a minute:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="weekly_minute"
                                required>
                            <option selected></option>
                            {% for m in minute_list %}
                            <option value='{{m}}'>{{m}}</option>
                            {% endfor %}
                        </select>
                        <p class="fw-medium"><strong></strong>Select a day:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="weekly_day"
                                required>
                            <option selected></option>
                            {% for d in dow_list %}
                            <option value='{{d}}'>{{d}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-outline-primary" type="submit" name="weekly">Save changes</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-sm-4">
            <form class="form-control" method="post">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <p class="fw-bold fs-2">Monthly</p>
                    </div>
                    <div class="card-body">
                        <p class="fw-medium"><strong>Active settings</strong>:<br>
                             <strong class="text-primary">{{ monthly_settings }} / {{ monthly_settings.mode_settings }}</strong>
                        </p>
                        <p class="fw-medium"><strong></strong>Select an hour:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="monthly_hour"
                                required>
                            <option selected></option>
                            {% for h in hour_list %}
                            <option value='{{h}}'>{{h}}</option>
                            {% endfor %}
                        </select>
                        <p class="fw-medium"><strong></strong>Select a minute:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="monthly_minute"
                                required>
                            <option selected></option>
                            {% for m in minute_list %}
                            <option value='{{m}}'>{{m}}</option>
                            {% endfor %}
                        </select>
                        <p class="fw-medium"><strong></strong>Select a day:</p>
                        <select class="form-select required" aria-label="Default select example"
                                name="monthly_day"
                                required>
                            <option selected></option>
                            {% for d in dom_list %}
                            <option value='{{d}}'>{{d}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-outline-primary" type="submit" name="monthly">Save changes</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'newsletter/base.html'%}
{% load my_tags %}
{% block content %}


<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               href="{% url 'users:user_list'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Users list
            </a>

        </div>
    </header>


    <div class="row">
        <div class="col-sm-8 mb-3 mb-sm-0">
            <div class="card">

                <div class="card-header">
                    <h1>User info</h1>
                </div>

                <div class="card-body">
                    <strong>Email</strong> - {{ object }}<br><br>
                    <strong>Phone number</strong> - {{ object.phone }}<br><br>
                    <strong>Clients added by user </strong> - {{ user_clients }}<br><br>
                    <strong>Newsletters added by user </strong> - {{ newsletter_user }}<br><br>
                    <strong>Is manager</strong> - {% if object|has_group:"manager"%}Yes{% else %}No{% endif %}<br><br>
                    <strong>Is verified</strong> - {% if object.is_verified %}Yes{% else %}No{% endif %}<br><br>
                </div>
                <div class="card-footer">

                    {% if request.user.is_superuser %}
                        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                            <a class="btn btn-outline-info rounded-pill"
                               href="{% url 'users:user_form' object.pk %}">Edit</a>
                            <a class="btn btn-outline-danger rounded-pill"
                               href="{% url 'users:user_delete' object.pk %}">Delete</a>
                        </nav>
                    {% endif %}
                    {% if request.user != object and not object.is_superuser %}
                    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto float-end">
                    <form method="post">
                            {% csrf_token %}
                            <input type="hidden" name="pk_verify_toggle" value="{{ object.pk }}">
                            <button class="btn btn-outline-warning" type="submit" name="verify_toggle">
                                {% if object.is_verified %}Block{% else %}Unblock{% endif %}
                            </button>
                        </form>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'newsletter/base.html'%}
{% load my_tags %}
{% block content %}

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a class="icon-link icon-link-hover d-flex align-items-center link-body-emphasis text-decoration-none"
               style="margin-right: 30px;" href="{% url 'newsletter:index'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Main page
            </a>
        </div>

    </header>

    <div class="container d-flex justify-content-center align-items-start mt-3">
        <div class="container-fluid" style="max-height: 400px;
            overflow-y: auto;">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Is active</th>
                    <th scope="col">Is verified</th>
                    <th scope="col">Is manager</th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for object in object_list %}
                <tr class="sticky-top">
                    <th scope="row">{{ object.pk}}</th>
                    <td><a href="{% url 'users:user_detail' object.pk %}"><strong>{{ object.email }}</strong></a></td>
                    <td>{{ object.phone}}</td>
                    <td>{% if object.is_active %}Yes{% else %}No{% endif %}</td>
                    <td>{% if object.is_verified %}Yes{% else %}No{% endif %}</td>
                    <td>
                        {% if object|has_group:"manager" %}Yes{% else %}No{% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if user.is_superuser %}
    <div class="m-4 float-end">
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="btn btn-outline-primary rounded-pill"
               href="{% url 'users:user_form' %}">Add user</a>
        </nav>
    </div>
    {% endif %}
</div>
{% endblock %}